/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guests_ui;

/**
 *
 * @author User1
 */
public class guest_ui extends javax.swing.JFrame {

    /**
     * Creates new form guest_ui
     */
    public guest_ui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtthl = new javax.swing.JTextField();
        jlblwel = new javax.swing.JLabel();
        jTxtrd1 = new javax.swing.JTextField();
        jTxtrd2 = new javax.swing.JTextField();
        jBtncmp = new javax.swing.JButton();
        jPnllogo = new javax.swing.JPanel();
        jlbllogo = new javax.swing.JLabel();
        jPnlDisplay = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtcomres = new javax.swing.JTextArea();
        jBtnreg = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTxtrate = new javax.swing.JTextField();
        jCrate = new javax.swing.JCheckBox();
        jTxtres = new javax.swing.JTextField();
        jCrd1 = new javax.swing.JCheckBox();
        jCrd2 = new javax.swing.JCheckBox();
        jBtnclear = new javax.swing.JButton();
        jBtnpres = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 700));

        jTxtthl.setEditable(false);
        jTxtthl.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jTxtthl.setText("Energy Forecast Management System");
        jTxtthl.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTxtthl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtthlActionPerformed(evt);
            }
        });

        jlblwel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblwel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblwel.setText("Welcome to Energy Forecast.  You are on the guest page.  We compare your bills and provide the cost. ");
        jlblwel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlblwel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jlblwel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jTxtrd1.setEditable(false);
        jTxtrd1.setBackground(new java.awt.Color(255, 255, 255));
        jTxtrd1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTxtrd1.setText("0");
        jTxtrd1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTxtrd2.setEditable(false);
        jTxtrd2.setBackground(new java.awt.Color(255, 255, 255));
        jTxtrd2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTxtrd2.setText("0");
        jTxtrd2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBtncmp.setBackground(new java.awt.Color(102, 255, 102));
        jBtncmp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtncmp.setText("Compare");
        jBtncmp.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 51), new java.awt.Color(0, 153, 51)));
        jBtncmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtncmpActionPerformed(evt);
            }
        });

        jPnllogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images pr/Energy Forecast logo.png"))); // NOI18N

        javax.swing.GroupLayout jPnllogoLayout = new javax.swing.GroupLayout(jPnllogo);
        jPnllogo.setLayout(jPnllogoLayout);
        jPnllogoLayout.setHorizontalGroup(
            jPnllogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnllogoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jlbllogo))
        );
        jPnllogoLayout.setVerticalGroup(
            jPnllogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnllogoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jlbllogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnlDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Comparison Results");

        jTxtcomres.setColumns(20);
        jTxtcomres.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTxtcomres.setRows(5);
        jScrollPane1.setViewportView(jTxtcomres);

        jBtnreg.setBackground(new java.awt.Color(0, 153, 153));
        jBtnreg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnreg.setForeground(new java.awt.Color(255, 255, 255));
        jBtnreg.setText("+Register");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("To access more features please register");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPnlDisplayLayout = new javax.swing.GroupLayout(jPnlDisplay);
        jPnlDisplay.setLayout(jPnlDisplayLayout);
        jPnlDisplayLayout.setHorizontalGroup(
            jPnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlDisplayLayout.createSequentialGroup()
                .addGroup(jPnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlDisplayLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPnlDisplayLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlDisplayLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnreg, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPnlDisplayLayout.setVerticalGroup(
            jPnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnreg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTxtrate.setEditable(false);
        jTxtrate.setBackground(new java.awt.Color(255, 255, 255));
        jTxtrate.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTxtrate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jCrate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCrate.setText("Show rate");
        jCrate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCrate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrateActionPerformed(evt);
            }
        });

        jTxtres.setEditable(false);
        jTxtres.setBackground(new java.awt.Color(255, 255, 255));
        jTxtres.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        jCrd1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCrd1.setText("Enter Current Bill Reading 1:");
        jCrd1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCrd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrd1ActionPerformed(evt);
            }
        });

        jCrd2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCrd2.setText("Enter Past Bill Reading 2:");
        jCrd2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCrd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrd2ActionPerformed(evt);
            }
        });

        jBtnclear.setBackground(new java.awt.Color(255, 51, 51));
        jBtnclear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnclear.setText("Clear");
        jBtnclear.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 51), new java.awt.Color(0, 153, 51)));
        jBtnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnclearActionPerformed(evt);
            }
        });

        jBtnpres.setBackground(new java.awt.Color(255, 204, 51));
        jBtnpres.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnpres.setText("Print all");
        jBtnpres.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 51), new java.awt.Color(0, 153, 51)));
        jBtnpres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnpresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPnllogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtthl, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblwel, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jCrd1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jCrd2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(jCrate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnpres, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jBtncmp, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jBtnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtrd1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtrd2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtrate, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtres, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jPnlDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnllogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtthl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jlblwel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jCrd1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jCrd2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jCrate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnpres, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtncmp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtrd1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jTxtrd2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jTxtrate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jTxtres, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPnlDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtthlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtthlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtthlActionPerformed

    private void jCrd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrd1ActionPerformed
    if(jCrd1.isSelected ())
    {
        jTxtrd1.setEditable(true);
        jTxtrd1.setText("");
        jTxtrd1.requestFocus();
    }
    else
    {
     jTxtrd1.setEditable(false);
     jTxtrd1.setText("0");      
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jCrd1ActionPerformed

    private void jCrd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrd2ActionPerformed
    if(jCrd2.isSelected ())
    {
        jTxtrd2.setEditable(true);
        jTxtrd2.setText("");
        jTxtrd2.requestFocus();
    }
    else
    {
     jTxtrd2.setEditable(false);
     jTxtrd2.setText("0");      
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jCrd2ActionPerformed

    private void jCrateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrateActionPerformed
    double iRate = 3.50;
        if(jCrate.isSelected ())
    {
        String pRate = String.format("kWh %.2f", iRate);
        jTxtrate.setText(pRate);
    }
    else
    {
     jTxtrate.setText(null);
           
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jCrateActionPerformed

    private void jBtnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnclearActionPerformed
    jTxtrate.setText("");
    jTxtrd1.setText("0");
    jTxtrd2.setText("0");
    jTxtres.setText("");
    jTxtcomres.setText("");
    jCrd1.setSelected(false);
    jCrd2.setSelected(false);
    jCrate.setSelected(false);
    
            
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnclearActionPerformed

    private void jBtncmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtncmpActionPerformed
    if ((jCrd1.isSelected()) || (jCrd2.isSelected())) //|| (jCrate.isSelected()))
    {
        double read1 = Double.parseDouble(jTxtrd1.getText()) * 1;
        double read2 = Double.parseDouble(jTxtrd2.getText()) * 1;
        //double rrate = Double.parseDouble(jTxtrate.getText()) * 1;
        double cmptot =  read1 - read2;
        
        String totalcom = String.format("%.0f", cmptot);
        jTxtres.setText((String)totalcom);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtncmpActionPerformed

    private void jBtnpresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnpresActionPerformed

    double readings1 = Double.parseDouble(jTxtrd1.getText());
    double readings2 = Double.parseDouble(jTxtrd2.getText());
    double resu = Double.parseDouble(jTxtres.getText());
    //double ratings = Double.parseDouble(jTxtrate.getText());
    
    jTxtcomres.append("Comparison between the two readings done. \n\n" + 
            "Current bill reading: \n" + readings1 + "\n\nPast reading:\n" + readings2 + "\n\nConsumption in kWh:\n" + resu + 
            "\n\nThank you for using the solution! \n Calculated by Energy Forecast.");
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnpresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guest_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guest_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guest_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guest_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guest_ui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnclear;
    private javax.swing.JButton jBtncmp;
    private javax.swing.JButton jBtnpres;
    private javax.swing.JButton jBtnreg;
    private javax.swing.JCheckBox jCrate;
    private javax.swing.JCheckBox jCrd1;
    private javax.swing.JCheckBox jCrd2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPnlDisplay;
    private javax.swing.JPanel jPnllogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtcomres;
    private javax.swing.JTextField jTxtrate;
    private javax.swing.JTextField jTxtrd1;
    private javax.swing.JTextField jTxtrd2;
    private javax.swing.JTextField jTxtres;
    private javax.swing.JTextField jTxtthl;
    private javax.swing.JLabel jlbllogo;
    private javax.swing.JLabel jlblwel;
    // End of variables declaration//GEN-END:variables
}
