/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package users_ui;



/**
 *
 * @author User1
 */
public class user_ui extends javax.swing.JFrame {
    double firstnum;
    double secondnum;
    double result;
    
    String operations;

    /**
     * Creates new form user_ui
     */
    public user_ui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnllogo2 = new javax.swing.JPanel();
        jlbllogo2 = new javax.swing.JLabel();
        jTxthl2 = new javax.swing.JTextField();
        jlblwel2 = new javax.swing.JLabel();
        jCrdu2 = new javax.swing.JCheckBox();
        jCrateu = new javax.swing.JCheckBox();
        jCrdu1 = new javax.swing.JCheckBox();
        jTxtrateu = new javax.swing.JTextField();
        jTxtrdu1 = new javax.swing.JTextField();
        jTxtrdu2 = new javax.swing.JTextField();
        jTxtresu = new javax.swing.JTextField();
        jBtnres2 = new javax.swing.JButton();
        jBtnpres2 = new javax.swing.JButton();
        jBtnclear2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtcomresu = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jTxtcalDisplay = new javax.swing.JTextField();
        jBtnbks = new javax.swing.JButton();
        jBtn1 = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jBtndot = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtnclear = new javax.swing.JButton();
        jBtnami = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtnadd = new javax.swing.JButton();
        jBtnmin = new javax.swing.JButton();
        jBtnmul = new javax.swing.JButton();
        jBtndiv = new javax.swing.JButton();
        jBtnres = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jBtnvb = new javax.swing.JButton();
        jBtnvp = new javax.swing.JButton();
        jBtnsb = new javax.swing.JButton();
        jBtnuui = new javax.swing.JButton();
        jBtnaui = new javax.swing.JButton();
        jBtngui = new javax.swing.JButton();
        jBtnulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnllogo2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPnllogo2.setLayout(null);

        jlbllogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images pr/Energy Forecast logo.png"))); // NOI18N
        jPnllogo2.add(jlbllogo2);
        jlbllogo2.setBounds(10, 20, 203, 175);

        jTxthl2.setEditable(false);
        jTxthl2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jTxthl2.setText("Energy Forecast Management System");
        jTxthl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxthl2ActionPerformed(evt);
            }
        });

        jlblwel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblwel2.setText("Welcome to Energy Forecast.  You are on the customer page.  We compare your bills and provide the cost. ");
        jlblwel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jCrdu2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCrdu2.setText("Enter Past Bill Reading 2:");
        jCrdu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrdu2ActionPerformed(evt);
            }
        });

        jCrateu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCrateu.setText("Show rate:");
        jCrateu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrateuActionPerformed(evt);
            }
        });

        jCrdu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCrdu1.setText("Enter Current Bill Reading 1:");
        jCrdu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrdu1ActionPerformed(evt);
            }
        });

        jTxtrateu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtrateu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTxtrdu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtrdu1.setText("0");
        jTxtrdu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtrdu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtrdu1ActionPerformed(evt);
            }
        });

        jTxtrdu2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtrdu2.setText("0");
        jTxtrdu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtrdu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtrdu2ActionPerformed(evt);
            }
        });

        jTxtresu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtresu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBtnres2.setBackground(new java.awt.Color(102, 255, 102));
        jBtnres2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnres2.setText("Compare");
        jBtnres2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnres2ActionPerformed(evt);
            }
        });

        jBtnpres2.setBackground(new java.awt.Color(255, 204, 51));
        jBtnpres2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnpres2.setText("Print all");
        jBtnpres2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnpres2ActionPerformed(evt);
            }
        });

        jBtnclear2.setBackground(new java.awt.Color(255, 51, 51));
        jBtnclear2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnclear2.setText("Clear");
        jBtnclear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnclear2ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jTxtcomresu.setEditable(false);
        jTxtcomresu.setColumns(20);
        jTxtcomresu.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTxtcomresu.setRows(5);
        jScrollPane1.setViewportView(jTxtcomresu);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Comparison results", jPanel2);

        jTxtcalDisplay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jBtnbks.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtnbks.setText("<-");
        jBtnbks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnbksActionPerformed(evt);
            }
        });

        jBtn1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });

        jBtn4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });

        jBtn7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });

        jBtn0.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtn0.setText("0");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });

        jBtndot.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtndot.setText(".");
        jBtndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtndotActionPerformed(evt);
            }
        });

        jBtn8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });

        jBtn5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });

        jBtn2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });

        jBtnclear.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtnclear.setText("C");
        jBtnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnclearActionPerformed(evt);
            }
        });

        jBtnami.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtnami.setText("+/-");
        jBtnami.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnamiActionPerformed(evt);
            }
        });

        jBtn3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });

        jBtn6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });

        jBtn9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });

        jBtnadd.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtnadd.setText("+");
        jBtnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnaddActionPerformed(evt);
            }
        });

        jBtnmin.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtnmin.setText("-");
        jBtnmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnminActionPerformed(evt);
            }
        });

        jBtnmul.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtnmul.setText("*");
        jBtnmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnmulActionPerformed(evt);
            }
        });

        jBtndiv.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtndiv.setText("/");
        jBtndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtndivActionPerformed(evt);
            }
        });

        jBtnres.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBtnres.setText("=");
        jBtnres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtcalDisplay)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnbks)
                            .addComponent(jBtn1)
                            .addComponent(jBtn4)
                            .addComponent(jBtn7)
                            .addComponent(jBtn0))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtndot)
                            .addComponent(jBtn8)
                            .addComponent(jBtn5)
                            .addComponent(jBtn2)
                            .addComponent(jBtnclear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtn9)
                                    .addComponent(jBtn6)
                                    .addComponent(jBtn3)
                                    .addComponent(jBtnami))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtndiv)
                                    .addComponent(jBtnmul)
                                    .addComponent(jBtnmin)
                                    .addComponent(jBtnadd)))
                            .addComponent(jBtnres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jTxtcalDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jBtnbks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn0))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jBtnclear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn8))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jBtnami)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn9))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jBtnadd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnmin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnmul)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtndiv)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtndot)
                            .addComponent(jBtnres))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Calculator", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("VP", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("SB", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("VB", jPanel6);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(30, 20, 390, 350);

        jBtnvb.setBackground(new java.awt.Color(204, 204, 255));
        jBtnvb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnvb.setText("View Bills (VB)");

        jBtnvp.setBackground(new java.awt.Color(204, 204, 255));
        jBtnvp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnvp.setText("View Profile (VP)");

        jBtnsb.setBackground(new java.awt.Color(204, 204, 255));
        jBtnsb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnsb.setText("Search Bills (SB)");

        jBtnuui.setText("User_ui");

        jBtnaui.setText("Admin_ui");

        jBtngui.setText("Guest_ui");

        jBtnulo.setBackground(new java.awt.Color(255, 51, 51));
        jBtnulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnulo.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPnllogo2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxthl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblwel2, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(jBtngui, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jBtnuui, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnaui, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnulo))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnvp)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jBtnvb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnsb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jCrdu1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jCrdu2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(jCrateu))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnpres2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jBtnres2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jBtnclear2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtrdu1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtrdu2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtrateu, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtresu, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(434, 434, 434))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnllogo2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxthl2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBtnuui, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtnaui, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtngui, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jBtnulo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblwel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jBtnvp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jBtnsb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jBtnvb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jCrdu1)
                        .addGap(39, 39, 39)
                        .addComponent(jCrdu2)
                        .addGap(49, 49, 49)
                        .addComponent(jCrateu)
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnpres2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnres2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnclear2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTxtrdu1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jTxtrdu2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTxtrateu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTxtresu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxthl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxthl2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxthl2ActionPerformed

    private void jTxtrdu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtrdu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtrdu1ActionPerformed

    private void jBtnresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnresActionPerformed
     String answer;
    secondnum = Double.parseDouble(jTxtcalDisplay.getText());
    if (operations == "+")
    {
        result = firstnum + secondnum;
        answer = String.format("%.0f", result);
        jTxtcalDisplay.setText(answer);
    }
    else if (operations == "-")
    {
     result = firstnum - secondnum;
     answer = String.format("%.0f", result);
     jTxtcalDisplay.setText(answer);   
    }
    else if (operations == "*")
    {
     result = firstnum * secondnum;
     answer = String.format("%.0f", result);
     jTxtcalDisplay.setText(answer);   
    }
    else if (operations == "/")
    {
     result = firstnum / secondnum;
     answer = String.format("%.0f", result);
     jTxtcalDisplay.setText(answer);   
    }
    
    else if (operations == "%")
    {
     result = firstnum % secondnum;
     answer = String.format("%.0f", result);
     jTxtcalDisplay.setText(answer);   
    }    // TODO add your handling code here:
    }//GEN-LAST:event_jBtnresActionPerformed

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
    String Enternumber = jTxtcalDisplay.getText() + jBtn1.getText();
    jTxtcalDisplay.setText(Enternumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
    String Enternumber = jTxtcalDisplay.getText() + jBtn2.getText();
    jTxtcalDisplay.setText(Enternumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
    String Enternumber = jTxtcalDisplay.getText() + jBtn3.getText();
    jTxtcalDisplay.setText(Enternumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
    String Enternumber = jTxtcalDisplay.getText() + jBtn4.getText();
    jTxtcalDisplay.setText(Enternumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
    String Enternumber = jTxtcalDisplay.getText() + jBtn5.getText();
    jTxtcalDisplay.setText(Enternumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
    String Enternumber = jTxtcalDisplay.getText() + jBtn6.getText();
    jTxtcalDisplay.setText(Enternumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
    String Enternumber = jTxtcalDisplay.getText() + jBtn7.getText();
    jTxtcalDisplay.setText(Enternumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
    String Enternumber = jTxtcalDisplay.getText() + jBtn8.getText();
    jTxtcalDisplay.setText(Enternumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
    String Enternumber = jTxtcalDisplay.getText() + jBtn9.getText();
    jTxtcalDisplay.setText(Enternumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed
    String Enternumber = jTxtcalDisplay.getText() + jBtn0.getText();
    jTxtcalDisplay.setText(Enternumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn0ActionPerformed

    private void jBtnminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnminActionPerformed
    firstnum = Double.parseDouble(jTxtcalDisplay.getText());
    jTxtcalDisplay.setText("");
    operations = "-";    // TODO add your handling code here:
    }//GEN-LAST:event_jBtnminActionPerformed

    private void jBtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnaddActionPerformed
    firstnum = Double.parseDouble(jTxtcalDisplay.getText());
    jTxtcalDisplay.setText("");
    operations = "+"; 
    // TODO add your handling code here:
    }//GEN-LAST:event_jBtnaddActionPerformed

    private void jBtnmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnmulActionPerformed
    firstnum = Double.parseDouble(jTxtcalDisplay.getText());
    jTxtcalDisplay.setText("");
    operations = "*"; 
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnmulActionPerformed

    private void jBtndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtndivActionPerformed
    firstnum = Double.parseDouble(jTxtcalDisplay.getText());
    jTxtcalDisplay.setText("");
    operations = "/"; 
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtndivActionPerformed

    private void jBtndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtndotActionPerformed
    firstnum = Double.parseDouble(jTxtcalDisplay.getText());
        jTxtcalDisplay.setText("");
        operations = ".";  
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtndotActionPerformed

    private void jBtnamiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnamiActionPerformed
    double ops = Double.parseDouble(String.valueOf(jTxtcalDisplay.getText()));
    ops = ops * (-1);
    jTxtcalDisplay.setText(String.valueOf(ops));    
        
// TODO add your handling code here:
    }//GEN-LAST:event_jBtnamiActionPerformed

    private void jBtnbksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnbksActionPerformed
    String backspace = null;
    
    if(jTxtcalDisplay.getText().length() > 0){
        StringBuilder strB = new StringBuilder(jTxtcalDisplay.getText());
        strB.deleteCharAt(jTxtcalDisplay.getText().length() -1);
        backspace = strB.toString();
        jTxtcalDisplay.setText(backspace);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnbksActionPerformed

    private void jBtnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnclearActionPerformed
    jTxtcalDisplay.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnclearActionPerformed

    private void jCrdu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrdu1ActionPerformed
     if(jCrdu1.isSelected ())
    {
        jTxtrdu1.setEditable(true);
        jTxtrdu1.setText("");
        jTxtrdu1.requestFocus();
    }
    else
    {
     jTxtrdu1.setEditable(false);
     jTxtrdu1.setText("0");      
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jCrdu1ActionPerformed

    private void jTxtrdu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtrdu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtrdu2ActionPerformed

    private void jCrdu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrdu2ActionPerformed
      if(jCrdu2.isSelected ())
    {
        jTxtrdu2.setEditable(true);
        jTxtrdu2.setText("");
        jTxtrdu2.requestFocus();
    }
    else
    {
     jTxtrdu2.setEditable(false);
     jTxtrdu2.setText("0");      
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jCrdu2ActionPerformed

    private void jCrateuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrateuActionPerformed
    double iRateu = 3.50;
        if(jCrateu.isSelected ())
    {
        String pRateu = String.format("kWh %.2f", iRateu);
        jTxtrateu.setText(pRateu);
    }
    else
    {
     jTxtrateu.setText(null);
           
    }    // TODO add your handling code here:
    }//GEN-LAST:event_jCrateuActionPerformed

    private void jBtnclear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnclear2ActionPerformed
    jTxtrateu.setText("");
    jTxtrdu1.setText("0");
    jTxtrdu2.setText("0");
    jTxtresu.setText("");
    jTxtcomresu.setText("");
    jCrdu1.setSelected(false);
    jCrdu2.setSelected(false);
    jCrateu.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnclear2ActionPerformed

    private void jBtnpres2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnpres2ActionPerformed
    double readings1 = Double.parseDouble(jTxtrdu1.getText());
    double readings2 = Double.parseDouble(jTxtrdu2.getText());
    double resu = Double.parseDouble(jTxtresu.getText());
    //double ratings = Double.parseDouble(jTxtrate.getText());
    
    jTxtcomresu.append("Comparison between the two readings done. \n\n" + 
            "Current bill reading: \n" + readings1 + "\n\nPast reading:\n" + readings2 + "\n\nConsumption in kWh:\n" + resu + 
            "\n\nThank you for using the solution! \n Calculated by Energy Forecast.");
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnpres2ActionPerformed

    private void jBtnres2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnres2ActionPerformed
     if ((jCrdu1.isSelected()) || (jCrdu2.isSelected())) //|| (jCrate.isSelected()))
    {
        double read1 = Double.parseDouble(jTxtrdu1.getText()) * 1;
        double read2 = Double.parseDouble(jTxtrdu2.getText()) * 1;
        //double rrate = Double.parseDouble(jTxtrate.getText()) * 1;
        double cmptot =  read1 - read2;
        
        String totalcom = String.format("%.0f", cmptot);
        jTxtresu.setText((String)totalcom);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnres2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_ui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnadd;
    private javax.swing.JButton jBtnami;
    private javax.swing.JButton jBtnaui;
    private javax.swing.JButton jBtnbks;
    private javax.swing.JButton jBtnclear;
    private javax.swing.JButton jBtnclear2;
    private javax.swing.JButton jBtndiv;
    private javax.swing.JButton jBtndot;
    private javax.swing.JButton jBtngui;
    private javax.swing.JButton jBtnmin;
    private javax.swing.JButton jBtnmul;
    private javax.swing.JButton jBtnpres2;
    private javax.swing.JButton jBtnres;
    private javax.swing.JButton jBtnres2;
    private javax.swing.JButton jBtnsb;
    private javax.swing.JButton jBtnulo;
    private javax.swing.JButton jBtnuui;
    private javax.swing.JButton jBtnvb;
    private javax.swing.JButton jBtnvp;
    private javax.swing.JCheckBox jCrateu;
    private javax.swing.JCheckBox jCrdu1;
    private javax.swing.JCheckBox jCrdu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPnllogo2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTxtcalDisplay;
    private javax.swing.JTextArea jTxtcomresu;
    private javax.swing.JTextField jTxthl2;
    private javax.swing.JTextField jTxtrateu;
    private javax.swing.JTextField jTxtrdu1;
    private javax.swing.JTextField jTxtrdu2;
    private javax.swing.JTextField jTxtresu;
    private javax.swing.JLabel jlbllogo2;
    private javax.swing.JLabel jlblwel2;
    // End of variables declaration//GEN-END:variables
}
