/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admins_ui;



import foresreg.forereg;
import guests_ui.guest_ui;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author User1
 */
public class admin_ui extends javax.swing.JFrame {
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet sr = null;
    
        
    

    /**
     * Creates new form admin_ui
     */
    public admin_ui() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnllogo3 = new javax.swing.JPanel();
        jlbllogo2 = new javax.swing.JLabel();
        jBtnsuab = new javax.swing.JButton();
        jBtnvuab = new javax.swing.JButton();
        jBtnvuap = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jproTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jBtnadnu = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jubillTable = new javax.swing.JTable();
        jBtnadminlo = new javax.swing.JButton();
        jBtnrmov = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnllogo3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlbllogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images pr/Energy Forecast logo.png"))); // NOI18N

        javax.swing.GroupLayout jPnllogo3Layout = new javax.swing.GroupLayout(jPnllogo3);
        jPnllogo3.setLayout(jPnllogo3Layout);
        jPnllogo3Layout.setHorizontalGroup(
            jPnllogo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnllogo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbllogo2)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPnllogo3Layout.setVerticalGroup(
            jPnllogo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnllogo3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jlbllogo2)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jBtnsuab.setBackground(new java.awt.Color(204, 204, 255));
        jBtnsuab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnsuab.setText("Search User's Bills (SUB)");
        jBtnsuab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jBtnvuab.setBackground(new java.awt.Color(204, 204, 255));
        jBtnvuab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnvuab.setText("View User's Bills (VUB)");
        jBtnvuab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnvuab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnvuabActionPerformed(evt);
            }
        });

        jBtnvuap.setBackground(new java.awt.Color(204, 204, 255));
        jBtnvuap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnvuap.setText("View User's Profiles (VUP)");
        jBtnvuap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnvuap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnvuapActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jproTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "user_id", "user_fname", "user_lname", "user_address", "user_address", "user_pass"
            }
        ));
        jScrollPane3.setViewportView(jproTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View User Profiles", jPanel2);

        jBtnadnu.setBackground(new java.awt.Color(204, 255, 0));
        jBtnadnu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnadnu.setText("Add New User");
        jBtnadnu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnadnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnadnuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jBtnadnu, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(659, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jBtnadnu, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add users", jPanel3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1036, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("SUB", jPanel6);

        jubillTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Bill_ID", "Bill_Read_1", "Bill_Read_2", "Bill_Reads_Consumption", "Bills_Cost", "User_ID"
            }
        ));
        jScrollPane1.setViewportView(jubillTable);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("VUB", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jBtnadminlo.setBackground(new java.awt.Color(255, 51, 51));
        jBtnadminlo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnadminlo.setText("Logout");
        jBtnadminlo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnadminlo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnadminloActionPerformed(evt);
            }
        });

        jBtnrmov.setBackground(new java.awt.Color(255, 0, 51));
        jBtnrmov.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnrmov.setText("Remove Users");
        jBtnrmov.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnrmov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnrmovActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnllogo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jBtnrmov, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnvuab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnsuab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnvuap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnadminlo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPnllogo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jBtnvuap, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jBtnsuab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jBtnvuab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnrmov, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jBtnadminlo)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(115, 115, 115))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnadminloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnadminloActionPerformed
    guest_ui ur = new guest_ui();
    ur.setVisible(true);
    ur.pack();
    ur.setLocationRelativeTo(null);
    ur.setExtendedState(JFrame.MAXIMIZED_BOTH);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnadminloActionPerformed

    private void jBtnvuapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnvuapActionPerformed
        showTable();

  // TODO add your handling code here:
    }//GEN-LAST:event_jBtnvuapActionPerformed

    private void jBtnadnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnadnuActionPerformed
        forereg rgfu = new forereg();
        rgfu.setVisible(true);
        rgfu.pack();
        rgfu.setLocationRelativeTo(null);
        rgfu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnadnuActionPerformed

    private void jBtnrmovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnrmovActionPerformed
    
    //Selected row function
    try{
        DefaultTableModel model = (DefaultTableModel) jproTable.getModel();    
        int SelectedRowIndex = jproTable.getSelectedRow();
        model.removeRow(SelectedRowIndex);
    }catch (Exception ex)
    {
        JOptionPane.showMessageDialog(null, ex);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnrmovActionPerformed

    private void jBtnvuabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnvuabActionPerformed
    showBillsTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnvuabActionPerformed
 public void showTable(){
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/energy_forecast_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "root", "");
            String sql = "SELECT * FROM `registered_users`";
            pst = con.prepareStatement(sql);
            sr = pst.executeQuery();
            jproTable.setModel(DbUtils.resultSetToTableModel(sr));
            
           
            
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            
            
            
        }}
 
  public void showBillsTable(){
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/energy_forecast_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "root", "");
            String sql = "SELECT * FROM `bills`";
            pst = con.prepareStatement(sql);
            sr = pst.executeQuery();
            jubillTable.setModel(DbUtils.resultSetToTableModel(sr));
            
           
            
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            
            
            
        }}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_ui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnadminlo;
    private javax.swing.JButton jBtnadnu;
    private javax.swing.JButton jBtnrmov;
    private javax.swing.JButton jBtnsuab;
    private javax.swing.JButton jBtnvuab;
    private javax.swing.JButton jBtnvuap;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPnllogo3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlbllogo2;
    private javax.swing.JTable jproTable;
    private javax.swing.JTable jubillTable;
    // End of variables declaration//GEN-END:variables
}
