
import javax.swing.JFrame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import users_ui.user_ui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User1
 */
public class Login_Form extends javax.swing.JFrame {

    /**
     * Creates new form Login_Form
     */
    public Login_Form() {
        initComponents();
        this.setLocationRelativeTo(null); // center format
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbllogi = new javax.swing.JLabel();
        jlblclos = new javax.swing.JLabel();
        jlblminimise = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlbluna = new javax.swing.JLabel();
        jlblpwd = new javax.swing.JLabel();
        jTxtuna2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jBtnlog = new javax.swing.JButton();
        jBtncancel = new javax.swing.JButton();
        jlblnreg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));
        jPanel1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jPanel1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        jlbllogi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbllogi.setForeground(new java.awt.Color(255, 255, 255));
        jlbllogi.setText("Login");

        jlblclos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblclos.setForeground(new java.awt.Color(255, 255, 255));
        jlblclos.setText("X");
        jlblclos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlblclos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblclosMouseClicked(evt);
            }
        });

        jlblminimise.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblminimise.setForeground(new java.awt.Color(255, 255, 255));
        jlblminimise.setText("-");
        jlblminimise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlblminimise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblminimiseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbllogi)
                .addGap(270, 270, 270)
                .addComponent(jlblminimise)
                .addGap(18, 18, 18)
                .addComponent(jlblclos))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbllogi)
                    .addComponent(jlblminimise)
                    .addComponent(jlblclos)))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jlbluna.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbluna.setForeground(new java.awt.Color(255, 255, 255));
        jlbluna.setText("Username:");

        jlblpwd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblpwd.setForeground(new java.awt.Color(255, 255, 255));
        jlblpwd.setText("Password:");

        jTxtuna2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jBtnlog.setBackground(new java.awt.Color(0, 153, 51));
        jBtnlog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnlog.setForeground(new java.awt.Color(255, 255, 255));
        jBtnlog.setText("LOGIN");
        jBtnlog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnlogActionPerformed(evt);
            }
        });

        jBtncancel.setBackground(new java.awt.Color(204, 0, 0));
        jBtncancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtncancel.setForeground(new java.awt.Color(255, 255, 255));
        jBtncancel.setText("CANCEL");
        jBtncancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtncancelActionPerformed(evt);
            }
        });

        jlblnreg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblnreg.setForeground(new java.awt.Color(255, 255, 255));
        jlblnreg.setText("Click here to register");
        jlblnreg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlblnreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblnregMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbluna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtuna2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlblpwd)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jBtncancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnlog))
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblnreg)
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbluna)
                    .addComponent(jTxtuna2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblpwd)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnlog, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jlblnreg)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jPanel1CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1CaretPositionChanged

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jlblclosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblclosMouseClicked
    System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblclosMouseClicked

    private void jlblminimiseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblminimiseMouseClicked
    this.setState(JFrame.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblminimiseMouseClicked

    private void jlblnregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblnregMouseClicked
    Register_Form rgf = new Register_Form();
    rgf.setVisible(true);
    rgf.pack();
    rgf.setLocationRelativeTo(null);
    rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblnregMouseClicked

    private void jBtncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtncancelActionPerformed
    System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtncancelActionPerformed

    private void jBtnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnlogActionPerformed
    PreparedStatement as;
    ResultSet sr;
     String usrname = jTxtuna2.getText();
     String passw = String.valueOf(jPasswordField1.getPassword());
     
     String query = "SELECT * FROM `registered_users` WHERE `user_uname`=? AND `user_pass` =?";
     
        try {
            as = NumyConnection.getConnection().prepareStatement(query);
            as.setString(1, usrname);
            as.setString(2, passw);
            
            sr = as.executeQuery();
            
            if(sr.next())
            {
               user_ui ur = new user_ui();
               ur.setVisible(true);
               ur.pack();
               ur.setLocationRelativeTo(null);
               ur.setExtendedState(JFrame.MAXIMIZED_BOTH);
               
         
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Incorrect Username or Password");
                
            }
            
           
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnlogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtncancel;
    private javax.swing.JButton jBtnlog;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTxtuna2;
    private javax.swing.JLabel jlblclos;
    private javax.swing.JLabel jlbllogi;
    private javax.swing.JLabel jlblminimise;
    private javax.swing.JLabel jlblnreg;
    private javax.swing.JLabel jlblpwd;
    private javax.swing.JLabel jlbluna;
    // End of variables declaration//GEN-END:variables
}
