/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foresreg;

import foresLogin.foreLogin;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JFrame;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/**
 *
 * @author User1
 */
public class forereg extends javax.swing.JFrame {

    /**
     * Creates new form forereg
     */
    public forereg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlreg1 = new javax.swing.JPanel();
        jlblclos2 = new javax.swing.JLabel();
        jlblreg = new javax.swing.JLabel();
        jlblsmin2 = new javax.swing.JLabel();
        jPnlreg2 = new javax.swing.JPanel();
        jlblfna = new javax.swing.JLabel();
        jlblrpas = new javax.swing.JLabel();
        jTxtfna = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jBtnregi = new javax.swing.JButton();
        jBtnclea2 = new javax.swing.JButton();
        jlblrlog = new javax.swing.JLabel();
        jTxtsna = new javax.swing.JTextField();
        jlblpas2 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jlblsna = new javax.swing.JLabel();
        jlbluna2 = new javax.swing.JLabel();
        jTxtuna2 = new javax.swing.JTextField();
        jlbladd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtadd = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPnlreg1.setBackground(new java.awt.Color(255, 102, 51));
        jPnlreg1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlblclos2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblclos2.setForeground(new java.awt.Color(255, 255, 255));
        jlblclos2.setText("X");
        jlblclos2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlblclos2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jlblclos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblclos2MouseClicked(evt);
            }
        });

        jlblreg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblreg.setForeground(new java.awt.Color(255, 255, 255));
        jlblreg.setText("Register");
        jlblreg.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jlblsmin2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblsmin2.setForeground(new java.awt.Color(255, 255, 255));
        jlblsmin2.setText("-");
        jlblsmin2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlblsmin2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jlblsmin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblsmin2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPnlreg1Layout = new javax.swing.GroupLayout(jPnlreg1);
        jPnlreg1.setLayout(jPnlreg1Layout);
        jPnlreg1Layout.setHorizontalGroup(
            jPnlreg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlreg1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblsmin2)
                .addGap(18, 18, 18)
                .addComponent(jlblclos2)
                .addContainerGap())
            .addGroup(jPnlreg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPnlreg1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jlblreg)
                    .addContainerGap(276, Short.MAX_VALUE)))
        );
        jPnlreg1Layout.setVerticalGroup(
            jPnlreg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlreg1Layout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addGroup(jPnlreg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblclos2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblsmin2, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(jPnlreg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlreg1Layout.createSequentialGroup()
                    .addContainerGap(47, Short.MAX_VALUE)
                    .addComponent(jlblreg)
                    .addGap(1, 1, 1)))
        );

        jPnlreg2.setBackground(new java.awt.Color(0, 153, 153));

        jlblfna.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblfna.setForeground(new java.awt.Color(255, 255, 255));
        jlblfna.setText("Forename:");

        jlblrpas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblrpas.setForeground(new java.awt.Color(255, 255, 255));
        jlblrpas.setText("Retype:");

        jTxtfna.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jPasswordField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });

        jBtnregi.setBackground(new java.awt.Color(51, 153, 0));
        jBtnregi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnregi.setForeground(new java.awt.Color(255, 255, 255));
        jBtnregi.setText("Register");
        jBtnregi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnregi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnregiActionPerformed(evt);
            }
        });

        jBtnclea2.setBackground(new java.awt.Color(255, 51, 51));
        jBtnclea2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnclea2.setForeground(new java.awt.Color(255, 255, 255));
        jBtnclea2.setText("Close");
        jBtnclea2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnclea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnclea2ActionPerformed(evt);
            }
        });

        jlblrlog.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblrlog.setForeground(new java.awt.Color(255, 255, 255));
        jlblrlog.setText("Click here to login");
        jlblrlog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlblrlog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblrlogMouseClicked(evt);
            }
        });

        jTxtsna.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jlblpas2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblpas2.setForeground(new java.awt.Color(255, 255, 255));
        jlblpas2.setText("Password:");

        jPasswordField3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPasswordField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField3ActionPerformed(evt);
            }
        });

        jlblsna.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblsna.setForeground(new java.awt.Color(255, 255, 255));
        jlblsna.setText("Surname:");

        jlbluna2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbluna2.setForeground(new java.awt.Color(255, 255, 255));
        jlbluna2.setText("Username:");

        jTxtuna2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jlbladd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbladd.setForeground(new java.awt.Color(255, 255, 255));
        jlbladd.setText("Address:");

        jTxtadd.setColumns(20);
        jTxtadd.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTxtadd.setRows(5);
        jScrollPane1.setViewportView(jTxtadd);

        javax.swing.GroupLayout jPnlreg2Layout = new javax.swing.GroupLayout(jPnlreg2);
        jPnlreg2.setLayout(jPnlreg2Layout);
        jPnlreg2Layout.setHorizontalGroup(
            jPnlreg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlreg2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbladd)
                .addGroup(jPnlreg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlreg2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jBtnclea2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jBtnregi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlreg2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPnlreg2Layout.createSequentialGroup()
                .addGroup(jPnlreg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlreg2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jlblfna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtfna, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlreg2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jlblsna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtsna, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlreg2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jlbluna2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtuna2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlreg2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jlblpas2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlreg2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jlblrpas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlreg2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jlblrlog, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPnlreg2Layout.setVerticalGroup(
            jPnlreg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlreg2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPnlreg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblfna)
                    .addComponent(jTxtfna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPnlreg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblsna, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtsna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPnlreg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbluna2)
                    .addComponent(jTxtuna2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPnlreg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblpas2)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPnlreg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblrpas)
                    .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPnlreg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbladd)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPnlreg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnregi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnclea2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblrlog)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlreg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPnlreg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnlreg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPnlreg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlblclos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblclos2MouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblclos2MouseClicked

    private void jlblsmin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblsmin2MouseClicked
        this.setState(JFrame.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblsmin2MouseClicked

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jPasswordField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField3ActionPerformed

    private void jBtnclea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnclea2ActionPerformed
    System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnclea2ActionPerformed

    private void jlblrlogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblrlogMouseClicked
        foreLogin lgf = new foreLogin();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblrlogMouseClicked

    private void jBtnregiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnregiActionPerformed
    String forname = jTxtfna.getText();
    String sname = jTxtsna.getText();
    String usrname = jTxtuna2.getText();
    String npass = String.valueOf(jPasswordField2.getPassword());
    String nrpass = String.valueOf(jPasswordField3.getPassword());
    String address1 = jTxtadd.getText();
    
    if(forname.equals(""))
    {
        JOptionPane.showMessageDialog(null, "Enter Forename");  
    }
    else if(sname.equals(""))
    {
        JOptionPane.showMessageDialog(null, "Enter Surname");  
    }
    else if(usrname.equals(""))
    {
        JOptionPane.showMessageDialog(null, "Enter Username");  
    }
    
    else if(npass.equals(""))
    {
        JOptionPane.showMessageDialog(null, "Enter Password"); 
    }
    
    else if(!npass.equals(nrpass))
    {
        JOptionPane.showMessageDialog(null, "Passwords do not match!"); 
    }
    
    else if(address1.equals(""))
    {
        JOptionPane.showMessageDialog(null, "Enter Address");  
    }
    
    else if (checkUsername(usrname)){
            JOptionPane.showMessageDialog(null, "Username Already Exists!");
        }

    else {
        PreparedStatement ps;
        String query = "INSERT INTO `registered_users`( `user_fname`, `user_lname`, `user_address`, `user_uname`, `user_pass`) VALUES (?,?,?,?,?)"; 
        
        try {
            ps = NuConnection.getConnection().prepareStatement(query);
            
            ps.setString(1, forname);
            ps.setString(2, sname);
            ps.setString(3, address1);
            ps.setString(4, usrname);
            ps.setString(5, npass);
            
            if(ps.executeUpdate() > 0)
            {
                JOptionPane.showMessageDialog(null, "New User Add");
            }
            
// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(forereg.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    
    //PreparedStatement ps;
    //String query = "";
    
    //ps = MyConnection.getConnection().prepareStatement(query);
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnregiActionPerformed
    public boolean checkUsername(String username)
            {
                PreparedStatement ps;
                ResultSet sr;
                boolean checkUname = false;
                String query = "SELECT * FROM `registered_users` WHERE `user_uname`=?";
        try {
            ps = NuConnection.getConnection().prepareStatement(query);
            ps.setString(1, username);
            sr = ps.executeQuery();
            
            if(sr.next())
            {
                checkUname = true;
            }           
        }
        catch (SQLException ex){
            Logger.getLogger(forereg.class.getName()).log(Level.SEVERE, null, ex);
        }
        return checkUname;}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forereg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forereg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forereg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forereg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forereg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnclea2;
    private javax.swing.JButton jBtnregi;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPanel jPnlreg1;
    private javax.swing.JPanel jPnlreg2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtadd;
    private javax.swing.JTextField jTxtfna;
    private javax.swing.JTextField jTxtsna;
    private javax.swing.JTextField jTxtuna2;
    private javax.swing.JLabel jlbladd;
    private javax.swing.JLabel jlblclos2;
    private javax.swing.JLabel jlblfna;
    private javax.swing.JLabel jlblpas2;
    private javax.swing.JLabel jlblreg;
    private javax.swing.JLabel jlblrlog;
    private javax.swing.JLabel jlblrpas;
    private javax.swing.JLabel jlblsmin2;
    private javax.swing.JLabel jlblsna;
    private javax.swing.JLabel jlbluna2;
    // End of variables declaration//GEN-END:variables

    private static class NuConnection {
        public static Connection getConnection(){
    Connection con = null;
    try{
        Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/energy_forecast_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "root", "");
    } catch (Exception ex) {
        System.out.println(ex.getMessage());
    }
      
    return con;
    }}}
      

