/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foresLogin;

import foresreg.forereg;
import javax.swing.JFrame;

/**
 *
 * @author User1
 */
public class foreLogin extends javax.swing.JFrame {

    /**
     * Creates new form foreLogin
     */
    public foreLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnllog1 = new javax.swing.JPanel();
        jlblclos = new javax.swing.JLabel();
        jlbllogttl = new javax.swing.JLabel();
        jlblsmin = new javax.swing.JLabel();
        jPnllog2 = new javax.swing.JPanel();
        jlbluna = new javax.swing.JLabel();
        jlblpas = new javax.swing.JLabel();
        jTxtuna = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jBtnlog = new javax.swing.JButton();
        jBtnclea = new javax.swing.JButton();
        jlblregi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPnllog1.setBackground(new java.awt.Color(255, 102, 51));

        jlblclos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblclos.setForeground(new java.awt.Color(255, 255, 255));
        jlblclos.setText("X");
        jlblclos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlblclos.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jlblclos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblclosMouseClicked(evt);
            }
        });

        jlbllogttl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbllogttl.setForeground(new java.awt.Color(255, 255, 255));
        jlbllogttl.setText("Login to system");
        jlbllogttl.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jlblsmin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblsmin.setForeground(new java.awt.Color(255, 255, 255));
        jlblsmin.setText("-");
        jlblsmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlblsmin.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jlblsmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblsminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPnllog1Layout = new javax.swing.GroupLayout(jPnllog1);
        jPnllog1.setLayout(jPnllog1Layout);
        jPnllog1Layout.setHorizontalGroup(
            jPnllog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnllog1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblsmin)
                .addGap(18, 18, 18)
                .addComponent(jlblclos)
                .addContainerGap())
            .addGroup(jPnllog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPnllog1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jlbllogttl)
                    .addContainerGap(205, Short.MAX_VALUE)))
        );
        jPnllog1Layout.setVerticalGroup(
            jPnllog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnllog1Layout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addGroup(jPnllog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblclos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblsmin, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(jPnllog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnllog1Layout.createSequentialGroup()
                    .addContainerGap(47, Short.MAX_VALUE)
                    .addComponent(jlbllogttl)
                    .addGap(1, 1, 1)))
        );

        jPnllog2.setBackground(new java.awt.Color(0, 153, 153));

        jlbluna.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbluna.setForeground(new java.awt.Color(255, 255, 255));
        jlbluna.setText("Username:");

        jlblpas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblpas.setForeground(new java.awt.Color(255, 255, 255));
        jlblpas.setText("Password:");

        jTxtuna.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jBtnlog.setBackground(new java.awt.Color(51, 153, 0));
        jBtnlog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnlog.setForeground(new java.awt.Color(255, 255, 255));
        jBtnlog.setText("Login");

        jBtnclea.setBackground(new java.awt.Color(255, 51, 51));
        jBtnclea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnclea.setForeground(new java.awt.Color(255, 255, 255));
        jBtnclea.setText("Clear");

        jlblregi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblregi.setForeground(new java.awt.Color(255, 255, 255));
        jlblregi.setText("Click here to create new account");
        jlblregi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlblregi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblregiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPnllog2Layout = new javax.swing.GroupLayout(jPnllog2);
        jPnllog2.setLayout(jPnllog2Layout);
        jPnllog2Layout.setHorizontalGroup(
            jPnllog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnllog2Layout.createSequentialGroup()
                .addGroup(jPnllog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnllog2Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jBtnclea, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnlog, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnllog2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jlblregi))
                    .addGroup(jPnllog2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPnllog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPnllog2Layout.createSequentialGroup()
                                .addComponent(jlblpas)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnllog2Layout.createSequentialGroup()
                                .addComponent(jlbluna)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtuna, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(19, 19, 19))
        );
        jPnllog2Layout.setVerticalGroup(
            jPnllog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnllog2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPnllog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnllog2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jlbluna))
                    .addComponent(jTxtuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPnllog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnllog2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jlblpas))
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPnllog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnclea, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnlog, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jlblregi)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnllog2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPnllog1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnllog1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPnllog2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jlblsminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblsminMouseClicked
    this.setState(JFrame.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblsminMouseClicked

    private void jlblclosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblclosMouseClicked
    System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblclosMouseClicked

    private void jlblregiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblregiMouseClicked
    forereg rgf = new forereg();
    rgf.setVisible(true);
    rgf.pack();
    rgf.setLocationRelativeTo(null);
    rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblregiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(foreLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(foreLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(foreLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(foreLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new foreLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnclea;
    private javax.swing.JButton jBtnlog;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPanel jPnllog1;
    private javax.swing.JPanel jPnllog2;
    private javax.swing.JTextField jTxtuna;
    private javax.swing.JLabel jlblclos;
    private javax.swing.JLabel jlbllogttl;
    private javax.swing.JLabel jlblpas;
    private javax.swing.JLabel jlblregi;
    private javax.swing.JLabel jlblsmin;
    private javax.swing.JLabel jlbluna;
    // End of variables declaration//GEN-END:variables
}
